config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root 'groups#index'
    resources :users, only: [:edit, :update, :index]
    resources :groups, only: [:new, :create, :edit, :update] do
      resources :messages, only: [:index, :create]
      namespace :api do
        resources :messages, only: :index, defaults: { format: 'json' }
      end
    end
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :users, through: :members
  has_many :members
  has_many :messages
  


  def show_last_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
  
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :group
  belongs_to :user
  
  validates :text, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, through: :members
  has_many :members
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).where('id > ?', params[:last_id])
    
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action   :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_group, only: [:edit, :update]
  
  def index
  end
  def new
    @group = Group.new
    @group.users << current_user
  end
  def create
    @group = Group.new(create_params)
    @group.users << current_user
    if @group.save
    redirect_to group_messages_path(@group), notice: "グループを作成しました。"
    else
      render :new 
    end
  end
  def edit
  end
  def update
    if @group.update(create_params)
     @group.users << current_user
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'

    else
      render :edit
    end
  end
  
  private
  
  def create_params
    params.require(:group).permit(:name, user_ids: [])
  end
  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
    before_action :set_group
    
    def index
      @message = Message.new
      @messages = @group.messages.includes(:user)
      @groups = Group.all
    end
    def create
        @message = @group.messages.new(create_params)
       if @message.save
        respond_to do |format|
          format.html{redirect_to group_messages_path(@group),notice:"メッセージが送信されました。"}
          format.json
        end
       else
        @messages = @group.messages.includes(:user)
        flash.now[:alert] = 'メッセージを入力してください。'
        render :index
       end
    end

    private
  def create_params
    params.require(:message).permit(:text,:message,:image).merge(user_id: current_user.id)
  end
  def set_group
    @group = Group.find(params[:group_id])
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def index
    @users = User.where('name LIKE(?)',"#{params[:keyword]}%").where.not(id: current_user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =form_for @group  do |f|
    -# .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "グループ名",class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name,  class: "chat-group-form__input", placeholder: "グループを入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバーを追加",class:"chat-group-form__label",for: "user-search-field"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input.chat-group-form__input#user-search-field{placeholder:'追加したいユーザー名を入力してください', type:'text'}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label" チャットメンバー",class:"chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            = f.hidden_field  :name, name:"group[user_ids][]",id:"group_user_ids",value:"" 
          -@group.users.each do |user| 
            .chat-group-user.clearfix
              = user.name
              -unless current_user.name == user.name
                .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除 
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit class: "chat-group-form__action-btn" 

app/views/groups/index.html.haml
.wrapper
  .notification
    = render "layouts/side_bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f| 
    - if @group.errors.any? 
      .chat-group-form__errors
        %h2
          1件のエラーが発生しました。
          %ul
            %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "グループ名",class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループを入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバーを追加",class:"chat-group-form__label",for: "user-search-field"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input.chat-group-form__input#user-search-field{placeholder:'追加したいユーザー名を入力してください', type:'text'}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label" チャットメンバー",class:"chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            = f.hidden_field  :name, name:"group[user_ids][]",id:"group_user_ids"
            %p.chat-group-user__name
            = current_user.name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit class: "chat-group-form__action-btn"
        

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key
    

app/views/layouts/_side_bar.html.haml
.chat-side
  .side-header
    %p.side-header__name 
      = current_user.name
    %ul.user-menu
      %li
        = link_to new_group_path do 
          %i.fa.fa-edit.edit
      %li
        = link_to  edit_user_registration_path(current_user) do
          %i.fa.fa-cog.set
  .groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .group
          %p.group__name
            = group.name
          %p.group__text
            = group.show_last_message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/index.html.haml
.wrapper
  .notification
    = render partial: 'layouts/side_bar'
    .chat-main
      .main-header
        .main-header__wrapper
          .current-group
            .current-group__name
              = @group.name
            %ul.member-list
              Member :
              - @group.users.each do |member|
                %li.member-list__member
                  = member.name
          = link_to 'Edit', edit_group_path(@group),class:"main-header__edit-btn" 
      .messages
        - @messages.each do |message|
          .message{"data-message-id": "#{message.id}"}
            .upper-info
              %p.upper-info__user
                = message.user.name
              %p.upper-info__date
                %span{class: "supText"}
                  = message.created_at.strftime("%Y/%m/%d(%a) %H:%M:%S")
            .message__text
              = message.text
            .image
              = image_tag(message.image)
      .form
        = form_for [@group,@message] do |f|
          .new-message
            .input-box
              = f.text_field :text,class: "input-text",placeholder:"text a message"
              %label.label-image
                %i.fa.fa-image
                = f.file_field :image,class: "image-label__input"
            = f.submit value: "Send",class: "submit" ,"data-disable-with": "Send"
        


  